name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:testing

    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y git golang-go nodejs npm

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Mark checkout directory as safe
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Run build script
        run: ./build.sh

      - name: Run Go tests
        run: go test ./...

      - name: Run Frontend tests
        run: cd frontend_app && npm test
